### PR TITLE
Drop glance-image-sync replication frequency from every 5 mins to 1 min

### PR DESCRIPTION
**Pull request by mattt416**

### CODE REVIEW

**Comment by breu** [comment]
Do we have locking in the sync to catch cases where the sync takes more than a minute to complete and we could fire off more than one sync at a time?

**Comment by mattt416** [comment]
Hi @rackerjoe,

Not in the script that we deploy today, but I am reworking it and have a locking mechanism in place in that version:

https://github.com/mattt416/glance-image-sync-1/blob/cleanup_code/rcb/glance_image_sync.py#L217

-Matt

**Comment by breu** [comment]
Do you know which commit this was fixed in?

**Comment by willkelly** [comment]
I don't think this is fixed.  My dingus is all messed up, man.

**Comment by mattt416** [comment]
HAI GUYZ

**Pull request closed without merging**
